name: build and test and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Rename dummy file
        run: mv Services/Dummy_FirebaseConfig.razor Services/_FirebaseConfig.razor

      - name: Replace config placeholder
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: sed -i "s|\*|\"$CONFIG\"|" Services/_FirebaseConfig.razor

      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      - name: Publish .NET Core Project
        run: dotnet publish ./CerberPat.csproj -c:Release -p:GHPages=true -o release --nologo

      - name: Update base href in index.html
        run: sed -i 's|<base href="/" />|<base href="/Cerber-Patting-Simulator/" />|' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          token: ${{ secrets.TOKEN }}
          folder: release/wwwroot